Repository DeveloperAcademy-POSTECH/2024-MacC-A10-Akdong-Cookiez, pull requests merged in 2024-11, with the labels that each got.

#2 ✨ Feat: #1 지출 통계 그래프 구현
  .swiftlint.yml
Labels: 이오 🐥, Feat ✨, Help 🚨

#4 ⚙️Setting: 초기 구조 / 디자인 시스템
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/AppDelegate.swift
  AKCOO/App/Coordinator/AppCoordinator.swift
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/App/SceneDelegate.swift
  AKCOO/Base.lproj/Main.storyboard
  AKCOO/DesignSystem/Color/UIColor+AKColor.swift
  AKCOO/DesignSystem/Extensions/SetWindowBackground.swift
  AKCOO/DesignSystem/Extensions/UIColor+Hex.swift
  AKCOO/DesignSystem/Extensions/UIViewController+HideKeyboard.swift
  AKCOO/DesignSystem/Font/AKFontType.swift
  AKCOO/DesignSystem/Font/CustomFont.swift
  AKCOO/DesignSystem/Font/UIFont+AKFont.swift
  AKCOO/DesignSystem/Spacing/CGFloat+AkSpacing.swift
  AKCOO/Model/Entity/Budget.swift
  AKCOO/Model/Entity/Currency.swift
  AKCOO/Model/Entity/Expense.swift
  AKCOO/Model/Entity/Travel.swift
  AKCOO/Model/UseCase/ExpenseUseCase.swift
  AKCOO/Model/UseCase/TravelUseCase.swift
  AKCOO/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  AKCOO/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  AKCOO/Resources/Assets.xcassets/Contents.json
  AKCOO/Resources/Base.lproj/LaunchScreen.storyboard
  AKCOO/Resources/Info.plist
  AKCOO/Scene/Common/Coordinator/Coordinator.swift
  AKCOO/Scene/Common/Coordinator/CoordinatorFinishDelegate.swift
  AKCOO/Scene/Common/Coordinator/CoordinatorType.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseRecordViewController.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseSceneController.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseStatsViewController.swift
  AKCOO/Scene/ExpenseScene/Coordinator/ExpenseCoordinatorImp.swift
  AKCOO/Scene/ExpenseScene/Coordinator/Protocol/ExpenseCoordinator.swift
  AKCOO/Scene/ExpenseScene/View/Empty.swift
  AKCOO/Scene/TravelScene/Controller/TravelListSceneController.swift
  AKCOO/Scene/TravelScene/Controller/TravelNewSceneController.swift
  AKCOO/Scene/TravelScene/Coordinator/Protocol/TravelListCoordinator.swift
  AKCOO/Scene/TravelScene/Coordinator/Protocol/TravelNewCoordinator.swift
  AKCOO/Scene/TravelScene/Coordinator/TravelListCoordinatorImp.swift
  AKCOO/Scene/TravelScene/Coordinator/TravelNewCoordinatorImp.swift
  AKCOO/Scene/TravelScene/View/TravelTableView.swift
  AKCOO/Scene/TravelScene/View/TravelTableViewCell.swift
  AKCOO/Scene/TravelScene/View/TravelTableViewCell.xib
  AKCOO/SceneDelegate.swift
  AKCOO/ViewController.swift
  AKCOOTests/AKCOOTests.swift
  AKCOOUITests/AKCOOUITests.swift
  AKCOOUITests/AKCOOUITestsLaunchTests.swift
Labels: 보노 🦦, OnGoing 🙌

#9 ✨ Feat: #8 코디네이터 수정
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/Coordinator/AppCoordinator.swift
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/DesignSystem/Extensions/SetWindowBackground.swift
  AKCOO/Model/UseCase/ExpenseUseCaseImp.swift
  AKCOO/Model/UseCase/Interface/ExpenseUseCase.swift
  AKCOO/Model/UseCase/Interface/TravelUseCase.swift
  AKCOO/Model/UseCase/TravelUseCaseImp.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseRecordViewController.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseSceneController.swift
  AKCOO/Scene/ExpenseScene/Controller/ExpenseStatsViewController.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseRecordFactory.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseRecordFactoryImp.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseSceneFactory.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseSceneFactoryImp.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseStatsFactory.swift
  AKCOO/Scene/ExpenseScene/Controller/Factory/ExpenseStatsFactoryImp.swift
  AKCOO/Scene/ExpenseScene/Coordinator/ExpenseCoordinatorImp.swift
  AKCOO/Scene/ExpenseScene/Coordinator/Protocol/ExpenseCoordinator.swift
  AKCOO/Scene/ExpenseScene/Coordinator/Protocol/ExpenseRecordCoordinator.swift
  AKCOO/Scene/ExpenseScene/Coordinator/Protocol/ExpenseStatsCoordinator.swift
  AKCOO/Scene/TravelScene/Controller/Factory/TravelListSceneFactory.swift
  AKCOO/Scene/TravelScene/Controller/Factory/TravelListSceneFactoryImp.swift
  AKCOO/Scene/TravelScene/Controller/Factory/TravelNewSceneFactory.swift
  AKCOO/Scene/TravelScene/Controller/Factory/TravelNewSceneFactoryImp.swift
  AKCOO/Scene/TravelScene/Controller/TravelListSceneController.swift
  AKCOO/Scene/TravelScene/Coordinator/Protocol/TravelCoordinator.swift
  AKCOO/Scene/TravelScene/Coordinator/Protocol/TravelListCoordinator.swift
  AKCOO/Scene/TravelScene/Coordinator/Protocol/TravelNewCoordinator.swift
  AKCOO/Scene/TravelScene/Coordinator/TravelCoordinatorImp.swift
  AKCOO/Scene/TravelScene/Coordinator/TravelListCoordinatorImp.swift
  AKCOO/Scene/TravelScene/Coordinator/TravelNewCoordinatorImp.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#13 ✨ Feat: #12 여행리스트 화면 | 여행리스트 그리기
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/DesignSystem/Extensions/SetWindowBackground.swift
  AKCOO/Model/Entity/Travel.swift
  AKCOO/Resources/Assets.xcassets/arrowRight.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/arrowRight.imageset/arrowRight.png
  AKCOO/Scene/TravelScene/Controller/TravelListSceneController.swift
  AKCOO/Scene/TravelScene/Controller/TravelNewSceneController.swift
  AKCOO/Scene/TravelScene/View/CircleView.swift
  AKCOO/Scene/TravelScene/View/TravelTableView.swift
  AKCOO/Scene/TravelScene/View/TravelTableViewCell.swift
  AKCOO/Scene/TravelScene/View/TravelTableViewCell.xib
Labels: 티나 🎀, Feat ✨

#27 📃 Chore: SwiftLint 규칙 수정(변수명 길이 제한을 1로 고정)
  .swiftlint.yml
Labels: 이오 🐥, OnReview 🐥

#35 ✨ Feat: 물가 정보 가져오기
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Data/DTO/PriceResponseDTO.swift
  AKCOO/Data/Repository/JudgmentRepositoryImp.swift
  AKCOO/Data/Service/FirestoreConstants.swift
  AKCOO/Data/Service/FirestoreError.swift
  AKCOO/Data/Service/FirestoreService.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/Repository/JudgmentRepository.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#37 ✨ Feat: 사용자가 선택한 나라 저장/불러오기
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Data/Repository/RecordRepositoryImp.swift
  AKCOO/Data/Service/UserDefaultsConstants.swift
  AKCOO/Data/Service/UserDefaultsError.swift
  AKCOO/Data/Service/UserDefaultsService.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#39 ✨ Feat: 소비 기록 저장/불러오기
  .swiftlint.yml
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/AppDelegate.swift
  AKCOO/Data/Repository/RecordRepositoryImp.swift
  AKCOO/Data/Service/CoreDataError.swift
  AKCOO/Data/Service/CoreDataService.swift
  AKCOO/Data/Service/CountryProfile+fromEntity.swift
  AKCOO/Data/Service/CountryProfile+toEntity.swift
  AKCOO/Data/Service/ExternalJudgmentEntity+toEntity.swift
  AKCOO/Data/Service/UserQuestion+fromEntity.swift
  AKCOO/Data/Service/UserQuestion+toEntity.swift
  AKCOO/Data/Service/UserRecord+fromEntity.swift
  AKCOO/Data/Service/UserRecord+toEntity.swift
  AKCOO/Data/Service/UserRecordModel.xcdatamodeld/UserRecordModel.xcdatamodel/contents
  AKCOO/Domain/Entity/Judgmemt/Type/JudgmentType.swift
  AKCOO/Domain/Entity/User/UserRecord.swift
  AKCOO/Domain/UseCase/Interface/Repository/RecordRepository.swift
Labels: 이오 🐥, Feat ✨, OnWatingMerge⭐️

#44 ✨ Feat: #41 JudgmentReadyViewController 화면완성
  AKCOO.xcodeproj/project.pbxproj
  AKCOO.xcodeproj/xcshareddata/xcschemes/AKCOO.xcscheme
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/DesignSystem/Font/UIButton+AkFont.swift
  AKCOO/DesignSystem/String/String+FormatWithComma.swift
  AKCOO/Domain/Entity/Judgmemt/PreviousJudgment.swift
  AKCOO/Domain/Entity/User/UserQuestion.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentRepositoryMock.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/UseCase/JudgmentUseCase.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Bird/ForeignBird.swift
  AKCOO/Domain/ViewModel/Paper/PaperModel.swift
  AKCOO/Scene/Common/Extension/UILabel+PaperLabel.swift
  AKCOO/Scene/Common/Type/BirdCharacterImageType.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactory.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentEditViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentReadyViewController.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/EditTransition.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/StartTransition.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentReadyView.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/AmountMoneyTextField.swift
  AKCOO/Scene/JudgmentScene/View/Paper/CategorySettingView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/ClosedPaperView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/AmountMoneyTextField.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/CategorySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/CountrySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/CountrySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/OpenedPaperView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/BirdReactionCell.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionCharacterView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCollectionView.swift
  AKCOOTests/Components/AmountMoneyTextFieldTests.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#47 🐛 But: UserQuestion 변경에 따른 UserRecord와 mapping method 변경
  AKCOO.xcodeproj/project.pbxproj
  AKCOO.xcodeproj/xcshareddata/xcschemes/AKCOO.xcscheme
  AKCOO/Data/Service/UserQuestion+fromEntity.swift
  AKCOO/Data/Service/UserQuestion+toEntity.swift
  AKCOO/Data/Service/UserRecord+fromEntity.swift
  AKCOO/Data/Service/UserRecord+toEntity.swift
  AKCOO/Data/Service/UserRecordModel.xcdatamodeld/UserRecordModel.xcdatamodel/contents
  AKCOO/Domain/Entity/User/UserRecord.swift
Labels: 이오 🐥, Bug 🐛, OnReview 🐥

#48 Feat: #42 JudgmentCompletedViewcontroller
  AKCOO.xcodeproj/project.pbxproj
  AKCOO.xcodeproj/xcshareddata/xcschemes/AKCOO.xcscheme
  AKCOO/DesignSystem/Extensions/GradientStyle+bottomShade.swift
  AKCOO/Domain/Entity/Judgmemt/CountryAverageJudgment.swift
  AKCOO/Domain/Entity/Judgmemt/PreviousJudgment.swift
  AKCOO/Domain/Entity/Judgmemt/Protocol/Judgment.swift
  AKCOO/Domain/ViewModel/Bird/ForeignBird.swift
  AKCOO/Domain/ViewModel/Bird/LocalBird.swift
  AKCOO/Domain/ViewModel/Bird/PreviousDayBird.swift
  AKCOO/Domain/ViewModel/Bird/Protocol/BirdModel.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/ClosedPaperView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/BirdReactionCell.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/DetailGraphView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCollectionView.swift
Labels: 보노 🦦, Feat ✨, OnWatingMerge⭐️

#51 ✨ Feat: 카테고리, 나라에 맞춰 직전 소비 가져오기 구현
  AKCOO/Data/Repository/RecordRepositoryImp.swift
  AKCOO/Data/Service/CoreDataService.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#58 ✨ Feat: 직전 소비짹 문구 기준 구현
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Domain/Entity/Judgmemt/PreviousJudgment.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Bird/PreviousBird.swift
  AKCOO/Domain/ViewModel/Bird/PreviousDayBird.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCollectionView.swift
  AKCOO/Utils/Extension/Date+toCompactKoreanDateString.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#59 ✨ Feat: 짹짹이들 판단 문구 변경 반영
  AKCOO/Domain/Entity/Judgmemt/CountryAverageJudgment.swift
  AKCOO/Domain/Entity/Judgmemt/PreviousJudgment.swift
  AKCOO/Domain/Entity/Judgmemt/Protocol/Judgment.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Bird/BirdGenerator/BirdJudgmentGenerator+getDetail.swift
  AKCOO/Domain/ViewModel/Bird/BirdGenerator/ForeignBirdJudgmentGenerator.swift
  AKCOO/Domain/ViewModel/Bird/BirdGenerator/LocalBirdJudgmentGenerator.swift
  AKCOO/Domain/ViewModel/Bird/ForeignBird.swift
  AKCOO/Domain/ViewModel/Bird/LocalBird.swift
  AKCOO/Domain/ViewModel/Bird/PreviousBird.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/BirdReactionCell.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCollectionView.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#61 ✨ Feat: 그래프에 필요한 정보 추가
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Domain/ViewModel/Bird/BirdReactionGraphInfo.swift
  AKCOO/Domain/ViewModel/Bird/ForeignBird.swift
  AKCOO/Domain/ViewModel/Bird/LocalBird.swift
  AKCOO/Domain/ViewModel/Bird/PreviousBird.swift
  AKCOO/Domain/ViewModel/Bird/Protocol/BirdModel.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/DetailGraphView.swift
Labels: 이오 🐥, OnGoing 🙌, Feat ✨

#57 ✨ Feat: #40 StartTransition, EditTranstion 커스텀, BubbleText
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Data/Service/UserRecord+fromEntity.swift
  AKCOO/DesignSystem/SnapshotTransition/SnapshotTransition.swift
  AKCOO/Domain/Entity/User/UserRecord.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/UseCase/JudgmentUseCase.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Resources/Assets.xcassets/Bubble/Contents.json
  AKCOO/Resources/Assets.xcassets/Bubble/blueleft.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bubble/blueleft.imageset/blueleft.svg
  AKCOO/Resources/Assets.xcassets/Bubble/blueright.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bubble/blueright.imageset/blueright.svg
  AKCOO/Resources/Assets.xcassets/Bubble/whiteleft.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bubble/whiteleft.imageset/whiteleft.svg
  AKCOO/Resources/Assets.xcassets/Bubble/whiteright.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bubble/whiteright.imageset/whiteright.svg
  AKCOO/Scene/Common/Extension/Double+String.swift
  AKCOO/Scene/Common/Type/BirdCharacterImageType.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactory.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactoryImp.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentEditViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentReadyViewController.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinator.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/EditTransition.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/EditTransitionaler.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/JudgmentTransition.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/JudgmentTransitionaler.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/StartTransition.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentEditView.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentReadyView.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/ClosedPaperView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/AmountMoneyTextField.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/CategorySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/ChatBubbleView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/CountrySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/OpenedPaperView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/BirdReactionCell.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionCharacterView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/DetailGraphView.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#67 ✨ Feat: Particle View 추가
  AKCOO.xcodeproj/project.pbxproj
  AKCOO.xcodeproj/xcshareddata/xcschemes/AKCOO.xcscheme
  AKCOO/Resources/Assets.xcassets/Confetti/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/Omark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/Omark.imageset/Omark.svg
  AKCOO/Resources/Assets.xcassets/Confetti/Xmark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/Xmark.imageset/Xmark.svg
  AKCOO/Utils/ConfettiAnimation/ConfettiCenterVM.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiContainer.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiFrame.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiItem.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiType.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiUIView.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiView.swift
  AKCOO/Utils/ConfettiAnimation/Shapes.swift
  AKCOO/Utils/ConfettiAnimation/TestConfettiView.swift
Labels: 이오 🐥, OnGoing 🙌, Feat ✨, Conflict 💣

#64 ✨ Feat: 새들의 Detail에 강조 추가
  AKCOO/DesignSystem/Font/AKFontType.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Bird/LocalBird.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/BirdReactionTextView.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#69 ✨ Feat: #168 앱 아이콘 이미지 추가, info.plist 수출규정 정보 추가
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  AKCOO/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  AKCOO/Resources/Info.plist
Labels: Feat ✨, OnWatingMerge⭐️

#72 ✨ Feat: JudgmentRepositoryMock Data 추가
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentRepositoryMock.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#73 ✨ Feat: #70 Confetti JudgmentView에 연결
  AKCOO/Domain/Entity/Judgmemt/PreviousJudgment.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Bird/PreviousBird.swift
  AKCOO/Resources/Assets.xcassets/Confetti/Omark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/Xmark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/confettiOmark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/confettiOmark.imageset/Omark.svg
  AKCOO/Resources/Assets.xcassets/Confetti/confettiXmark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Confetti/confettiXmark.imageset/Xmark.svg
  AKCOO/Resources/Assets.xcassets/launchscreenBird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/launchscreenBird.imageset/launchscreenBird.svg
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactoryImp.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/JudgmentTransition.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiCenterVM.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiType.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiUIView.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiView.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiViewController.swift
  AKCOO/Utils/ConfettiAnimation/CounterViewModel.swift
  AKCOO/Utils/ConfettiAnimation/TestConfettiView.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#74 Feat/#65 launch screen UI
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Resources/Base.lproj/LaunchScreen.storyboard
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#75 ✨ Feat: #66 JudgmentUseCaseImp 로직 정리, RepositoryImp 연결
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Utils/ConfettiAnimation/ConfettiViewController.swift
Labels: 보노 🦦, OnGoing 🙌, Feat ✨
