Repository DeveloperAcademy-POSTECH/2024-MacC-A10-Akdong-Cookiez, pull requests merged in 2024-12, with the labels that each got.

#80 🧪 Test: BirdJudgmentGenerator - getReaction 테스트 코드 작성
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Domain/ViewModel/Bird/BirdConstants.swift
  AKCOO/Domain/ViewModel/Bird/BirdGenerator/ForeignBirdJudgmentGenerator.swift
  AKCOO/Domain/ViewModel/Bird/BirdGenerator/LocalBirdJudgmentGenerator.swift
  AKCOO/Utils/Extension/String+fillTemplate.swift
  AKCOOTests/AKCOO/Data/Service/CoreData/CoreData_EntityMappingTests.swift
  AKCOOTests/AKCOO/Domain/ViewModel/BirdJudgmentGenerator/BirdJudgmentGenerator_GetDetailTests.swift
  AKCOOTests/AKCOO/Domain/ViewModel/BirdJudgmentGenerator/BirdJudgmentGenerator_GetReactionTests.swift
  AKCOOTests/AKCOO/Domain/ViewModel/BirdJudgmentGenerator/ForeignBirdJudgmentGenerator_GetOpinionTests.swift
  AKCOOTests/AKCOO/Domain/ViewModel/BirdJudgmentGenerator/LocalBirdJudgmentGenerator_GetOpinionTests.swift
  AKCOOTests/AKCOO/Scene/Components/AmountMoneyTextFieldTests.swift
  AKCOOTests/Mock/MockCoreDataStack.swift
  AKCOOTests/Mock/MockCountryAverageJudgment.swift
  AKCOOTests/Mock/MockCountryProfile.swift
  AKCOOTests/Mock/MockItem.swift
  AKCOOTests/Mock/MockUserRecord.swift
Labels: 이오 🐥, OnReview 🐥, Test🧪

#83 Feat/#81 GuideCoordinator, UserInfoCoordinator 구조 설정
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/Domain/UseCase/GuideUseCaseImp.swift
  AKCOO/Domain/UseCase/Interface/Mock/GuideUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/Mock/UserInfoUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/Mock/VoidResponse.swift
  AKCOO/Domain/UseCase/Interface/UseCase/GuideUseCase.swift
  AKCOO/Domain/UseCase/Interface/UseCase/UserInfoUseCase.swift
  AKCOO/Domain/UseCase/UserInfoUseCaseImp.swift
  AKCOO/Scene/Common/Coordinator/CoordinatorType.swift
  AKCOO/Scene/GuideScene/Controller/Factory/GuideFactory.swift
  AKCOO/Scene/GuideScene/Controller/Factory/GuideFactoryImp.swift
  AKCOO/Scene/GuideScene/Controller/GuideViewController.swift
  AKCOO/Scene/GuideScene/Coordinator/GuideCoordinator.swift
  AKCOO/Scene/GuideScene/Coordinator/GuideCoordinatorImp.swift
  AKCOO/Scene/GuideScene/View/GuideView.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinator.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinatorImp.swift
  AKCOO/Scene/UserInfoScene/Controller/Factory/UserInfoFactory.swift
  AKCOO/Scene/UserInfoScene/Controller/Factory/UserInfoFactoryImp.swift
  AKCOO/Scene/UserInfoScene/Controller/UserInfoViewController.swift
  AKCOO/Scene/UserInfoScene/Coordinator/UserInfoCoordinator.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoView.swift
Labels: 보노 🦦, Feat ✨, OnWatingMerge⭐️

#90 ✨Feat: JudgmentReadyViewController, UserInfoViewController 뒤로가기 버튼
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Scene/GuideScene/Coordinator/GuideCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentReadyViewController.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentReadyView.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#91 ✨Feat: #87 GuideViewController 국가 선택 추가 및 기존 JudgmentView 국가 선택 기능 삭제, UseCase 리팩토링
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/DesignSystem/Font/AKFontType.swift
  AKCOO/Domain/UseCase/GuideUseCaseImp.swift
  AKCOO/Domain/UseCase/Interface/Mock/GuideUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/Mock/JudgmentUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/UseCase/GuideUseCase.swift
  AKCOO/Domain/UseCase/Interface/UseCase/JudgmentUseCase.swift
  AKCOO/Domain/UseCase/JudgmentUseCaseImp.swift
  AKCOO/Domain/ViewModel/Paper/PaperModel.swift
  AKCOO/Scene/GuideScene/Controller/GuideViewController.swift
  AKCOO/Scene/GuideScene/Coordinator/GuideCoordinator.swift
  AKCOO/Scene/GuideScene/Coordinator/GuideCoordinatorImp.swift
  AKCOO/Scene/GuideScene/View/CountrySelectorTitle.swift
  AKCOO/Scene/GuideScene/View/GuideView.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgementReadyFactory.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgementReadyFactoryImp.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactory.swift
  AKCOO/Scene/JudgmentScene/Controller/Factory/JudgmentCompletedFactoryImp.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentEditViewController.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentReadyViewController.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinator.swift
  AKCOO/Scene/JudgmentScene/Coordinator/JudgmentCoordinatorImp.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/EditTransition.swift
  AKCOO/Scene/JudgmentScene/Coordinator/Presenter/JudgmentTransition.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentEditView.swift
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentReadyView.swift
  AKCOO/Scene/JudgmentScene/View/Paper/Components/CountrySelector.swift
  AKCOO/Scene/JudgmentScene/View/Paper/OpenedPaperView.swift
Labels: 보노 🦦, Feat ✨, OnReview 🐥

#96 ✨ Feat: 사용자 판단 유형 데이터 연결 및 화면 변경 사항 반영
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/App/Coordinator/AppCoordinatorImp.swift
  AKCOO/Data/Repository/RecordRepositoryImp.swift
  AKCOO/Data/Service/CoreDataService.swift
  AKCOO/Domain/UseCase/Interface/Mock/RecordRepositoryMock.swift
  AKCOO/Domain/UseCase/Interface/Mock/UserInfoUseCaseMock.swift
  AKCOO/Domain/UseCase/Interface/Repository/RecordRepository.swift
  AKCOO/Domain/UseCase/Interface/UseCase/UserInfoUseCase.swift
  AKCOO/Domain/UseCase/UserInfoUseCaseImp.swift
  AKCOO/Domain/ViewModel/UserJudgmentType/UserJudgmentType.swift
  AKCOO/Domain/ViewModel/UserJudgmentType/UserJudgmentTypeModel.swift
  AKCOO/Resources/Assets.xcassets/emptyRecordBird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/emptyRecordBird.imageset/emptyRecordBird_2x.png
  AKCOO/Resources/Assets.xcassets/emptyRecordBird.imageset/emptyRecordBird_3x.png
  AKCOO/Scene/UserInfoScene/Controller/UserInfoViewController.swift
  AKCOO/Scene/UserInfoScene/View/Components/UserInfoBirdChatView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoBirdView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoDescriptionView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoRecordsView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoTitleView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoView.swift
Labels: 이오 🐥, Feat ✨, OnReview 🐥

#98 🐛 Fix: 사용자 판단이 중복 저장되는 문제 해결
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoDescriptionView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoRecordsView.swift
Labels: 이오 🐥, Bug 🐛

#100 ✨ Feat: 나라별 물가 정보 화면 구현
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/DesignSystem/Font/AKFontType.swift
  AKCOO/Domain/Entity/Standard/Item.swift
  AKCOO/Domain/UseCase/Interface/Mock/GuideUseCaseMock.swift
  AKCOO/Scene/GuideScene/Controller/GuideViewController.swift
  AKCOO/Scene/GuideScene/View/GuidePriceLevelByCountryView.swift
  AKCOO/Scene/GuideScene/View/GuideView.swift
Labels: 이오 🐥, Feat ✨

#105 🐛 Bug: v1.1.0 에서 발견된 오류 해결
  AKCOO/Resources/Assets.xcassets/userInfoButton.imageset/userInfoButton.svg
  AKCOO/Scene/GuideScene/View/GuidePriceLevelByCountryView.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCell/Components/DetailGraphView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoRecordsView.swift
Labels: 이오 🐥, Bug 🐛, OnReview 🐥

#107 🐛 Bug: 지출 판단에서 '살래요'로 저장되는 오류 해결
  AKCOO/Domain/ViewModel/UserJudgmentType/UserJudgmentTypeModel.swift
  AKCOO/Resources/Assets.xcassets/Bird/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbird.imageset/greenbird.svg
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdpointL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdpointL.imageset/greenbirdpointL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdpointR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdpointR.imageset/greenbirdpointR.svg
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdstanding.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdstanding.imageset/greenbirdstanding.svg
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdwingL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdwingL.imageset/greenbirdwingL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdwingR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Green/greenbirdwingR.imageset/greenbirdwingR.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbird.imageset/redbird.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdpointL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdpointL.imageset/redbirdpointL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdpointR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdpointR.imageset/redbirdpointR.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdstanding.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdstanding.imageset/redbirdstanding.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdwingL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdwingL.imageset/redbirdwingL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdwingR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Red/redbirdwingR.imageset/redbirdwingR.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbird.imageset/yellowbird.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdpointL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdpointL.imageset/yellowbirdpointL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdpointR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdpointR.imageset/yellowbirdpointR.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdstanding.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdstanding.imageset/yellowbirdstanding.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdwingL.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdwingL.imageset/yellowbirdwingL.svg
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdwingR.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/Yellow/yellowbirdwingR.imageset/yellowbirdwingR.svg
  AKCOO/Resources/Assets.xcassets/Bird/emptyRecordBird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/emptyRecordBird.imageset/emptyRecordBird_2x.png
  AKCOO/Resources/Assets.xcassets/Bird/emptyRecordBird.imageset/emptyRecordBird_3x.png
  AKCOO/Resources/Assets.xcassets/Bird/launchscreenBird.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/launchscreenBird.imageset/launchscreenBird.svg
  AKCOO/Resources/Assets.xcassets/Bird/userInfoButton.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/Bird/userInfoButton.imageset/userInfoButton.svg
  AKCOO/Resources/Assets.xcassets/UserRecord/Contents.json
  AKCOO/Resources/Assets.xcassets/UserRecord/userRecordOmark.imageset/Contents.json
  AKCOO/Resources/Assets.xcassets/UserRecord/userRecordOmark.imageset/Omark.svg
  AKCOO/Scene/JudgmentScene/View/Judgment/JudgmentView.swift
  AKCOO/Scene/UserInfoScene/View/UserInfoRecordsView.swift
Labels: 이오 🐥, Bug 🐛

#108 Hotfix: iOS 18.0에서 짹짹이 날아오는 애니메이션 삭제된 문제 개선
  AKCOO.xcodeproj/project.pbxproj
  AKCOO/Domain/ViewModel/Bird/ForeignBird.swift
  AKCOO/Scene/JudgmentScene/Controller/JudgmentCompletedViewController.swift
  AKCOO/Scene/JudgmentScene/View/Reaction/BirdReactionCollectionView.swift
Labels: 보노 🦦, Bug 🐛
